apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 388262664999.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 388262664999.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: e46fdd68
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
